#!/bin/bash
cd
mkdir /usr 1>/dev/null 2>/dev/null
rm squidv5.tar.gz 1>/dev/null 2>/dev/null
rm -r squid-5.0.0-20170209-r15039 >/dev/null 2>/dev/null
read -p "Digite seu ip: " ip
clear
rm /usr/sbin/squid >/dev/null 2>/dev/null
echo -e "\033[1;37m Instalando gcc make perl g++ curl e atualizando repositorios... \033[00m"
apt-get update >/dev/null 2>/dev/null
apt-get install make -y >/dev/null 2>/dev/null
apt-get install curl -y >/dev/null 2>/dev/null
apt-get install gcc -y >/dev/null 2>/dev/null
apt-get install g++ -y >/dev/null 2>/dev/null
apt-get install perl -y >/dev/null 2>/dev/null
curl -o squidv5.tar.gz -C - http://www.squid-cache.org/Versions/v5/squid-5.0.0-20170209-r15039.tar.gz --silent
tar -xf squidv5.tar.gz
cd squid-5.0.0-20170209-r15039/
echo -e "\033[1;37m Preparando arquivos e configurações para compilação (Make)\033[0m"
./configure --prefix=/usr --enable-shared --enable-icmp --enable-delay-pools --enable-sll --enable-linux-netfilter --enable-basic-auth-helpers=NCSA,LDAP,SMB >/dev/null 2>/dev/null
echo -e "\033[1;31m Compilando o Squid V5 \033[1;37m(Demora bastante)\033[0m"
echo -e "\033[1;37m Aperte qualquer tecla para continuar ou ctrl + c para sair\033[0m"
read inut
make install
clear
echo -e "\033[1;31m Compilação terminada"
echo -e "\033[1;37m Configurando /usr/etc/squid.conf\033[0m"
echo "cache_effective_user squid
cache_access_log /usr/var/logs/access.log
http_port 80
http_port 8080
acl accept dstdomain $ip" > /usr/etc/squid.conf
echo 'http_access allow accept
acl claroseguridad dstdomain -i .claroseguridad.com
http_access allow claroseguridad 
cache deny claroseguridad
acl permitidos dstdomain -i "/usr/etc/payloads"
http_access allow permitidos
acl local dstdomain localhost
acl local dstdomain 127.0.0.1
http_access allow local
http_access deny all
visible_hostname RickUX' >> /usr/etc/squid.conf
echo -e "\033[1;37m Criando usuario squid..\033[0m"
useradd -s /bin/false squid >/dev/null 2>/dev/null
mkdir /usr/var/cache /usr/var/logs >/dev/null 2>/dev/null
chown -R squid. /usr/var/cache /usr/var/logs
echo localhost >> /usr/etc/payloads
echo -e "\033[1;37m Inciando serviço do squid V5"
/usr/sbin/squid
/usr/sbin/squid -z >/dev/null 2>/dev/null
echo -e "\n\033[1;31m Comandos para squid v5 \033[1;37m
 /usr/sbin/squid # comando para iniciar o serviço do squid v5
 /usr/sbin/squid -k shutdown # comando para parar o serviço do squid v5
 /usr/sbin/squid -k reconfigure # comando para reconfigurar squid v5
 /usr/sbin/squid -k restart # comando para reiniciar squid v5
 
 Para saber mais execute /usr/sbin/squid --help\033[0m"
